'use client'

import { useState } from 'react'

export function AIExplanationDropdown({ text }: { text: string }) {
  const [open, setOpen] = useState(false)

  const paragraphs = text.split('\n\n').filter(Boolean)

  return (
    <div className="mt-3 border-t border-border pt-3">
      <button
        onClick={(e) => { e.preventDefault(); setOpen((v) => !v) }}
        className="flex items-center gap-2 group w-full text-left"
        aria-expanded={open}
      >
        <span className="font-mono text-[9px] tracking-widest px-1.5 py-0.5 rounded border border-signal-ai/30 bg-signal-ai/5 text-signal-ai shrink-0">
          AI
        </span>
        <span className="font-mono text-[10px] tracking-widest text-ink-4 group-hover:text-ink-3 transition-colors">
          PLAIN-LANGUAGE EXPLANATION
        </span>
        <span
          className={`ml-auto font-mono text-[10px] text-ink-4 transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
          aria-hidden="true"
        >
          ▾
        </span>
      </button>

      {open && (
        <div className="mt-3 space-y-3">
          {paragraphs.map((p, i) => (
            <p key={i} className="text-sm text-ink-3 leading-relaxed">
              {p}
            </p>
          ))}
          <p className="font-mono text-[9px] text-ink-4 pt-1">
            Generated by Claude · May contain inaccuracies · Verify against primary sources
          </p>
        </div>
      )}
    </div>
  )
}
